package com.vodimobile.presentation.theme

import androidx.compose.ui.graphics.Color

val primaryLight = Color(0xFF1958EE)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFA5BCF2)
val onPrimaryContainerLight = Color(0xFF939BAA)
val secondaryLight = Color(0xFF595D72)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFF6F6F6)
val onSecondaryContainerLight = Color(0xFF161B2C)
val tertiaryLight = Color(0xFF9CA3B0)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFFFD7F6)
val onTertiaryContainerLight = Color(0xFF2C122A)
val errorLight = Color(0xFFFF3B30)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD5)
val onErrorContainerLight = Color(0xFF3B0906)
val backgroundLight = Color(0xFFFFFFFF)
val onBackgroundLight = Color(0xFF1A1B21)
val surfaceLight = Color(0xFFFAF8FF)
val onSurfaceLight = Color(0xFF154CCF)
val surfaceVariantLight = Color(0xFFE2E1EC)
val onSurfaceVariantLight = Color(0xFF45464F)
val outlineLight = Color(0xFF767680)
val outlineVariantLight = Color(0xFFC6C6D0)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2F3036)
val inverseOnSurfaceLight = Color(0xFFF1F0F7)
val inversePrimaryLight = Color(0xFFB6C4FF)
val surfaceDimLight = Color(0xFFDAD9E0)
val surfaceBrightLight = Color(0xFFFAF8FF)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF4F3FA)
val surfaceContainerLight = Color(0xFFEEEDF4)
val surfaceContainerHighLight = Color(0xFFE9E7EF)
val surfaceContainerHighestLight = Color(0xFFE3E1E9)

val primaryDark = Color(0xFFB6C4FF)
val onPrimaryDark = Color(0xFF1D2D61)
val primaryContainerDark = Color(0xFF354479)
val onPrimaryContainerDark = Color(0xFFDCE1FF)
val secondaryDark = Color(0xFFC2C5DD)
val onSecondaryDark = Color(0xFF2B3042)
val secondaryContainerDark = Color(0xFF424659)
val onSecondaryContainerDark = Color(0xFFDEE1F9)
val tertiaryDark = Color(0xFFE3BADA)
val onTertiaryDark = Color(0xFF432740)
val tertiaryContainerDark = Color(0xFF5B3D57)
val onTertiaryContainerDark = Color(0xFFFFD7F6)
val errorDark = Color(0xFFFFB4AA)
val onErrorDark = Color(0xFF561E18)
val errorContainerDark = Color(0xFF73342C)
val onErrorContainerDark = Color(0xFFFFDAD5)
val backgroundDark = Color(0xFF121318)
val onBackgroundDark = Color(0xFFE3E1E9)
val surfaceDark = Color(0xFF121318)
val onSurfaceDark = Color(0xFFE3E1E9)
val surfaceVariantDark = Color(0xFF45464F)
val onSurfaceVariantDark = Color(0xFFC6C6D0)
val outlineDark = Color(0xFF90909A)
val outlineVariantDark = Color(0xFF45464F)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE3E1E9)
val inverseOnSurfaceDark = Color(0xFF2F3036)
val inversePrimaryDark = Color(0xFF4D5C92)
val surfaceDimDark = Color(0xFF121318)
val surfaceBrightDark = Color(0xFF38393F)
val surfaceContainerLowestDark = Color(0xFF0D0E13)
val surfaceContainerLowDark = Color(0xFF1A1B21)
val surfaceContainerDark = Color(0xFF1E1F25)
val surfaceContainerHighDark = Color(0xFF292A2F)
val surfaceContainerHighestDark = Color(0xFF34343A)

val divider = Color(0xFFCAC4D0)

val headerBackLight = Color(0xFFF3F6FE)
val questionCardLight = Color(0xFFF6F6F6)

val secondaryBackgroundLight = Color(0xFFF6F6F6)
val secondaryBackgroundDark = Color(0xFF141218)
val onSecondaryBackgroundLight = Color(0xFFFFFFFF)
val onSecondaryBackgroundDark = Color(0xFF1D1B20)
val hintTextLight = Color(0xFF939BAA)
val hintTextDark = Color(0xFF939BAA)