package com.vodimobile.presentation

import androidx.datastore.preferences.core.stringPreferencesKey

object TestTags {
    object FaqItem {
        val questionCard = "questionCard"
        val answerText = "answerText"
    }

    object RuleTitleItem {
        val ruleTitleItemText = "ruleTitleItemText"
    }

    object TestDataStore {
        val PREFERENCES_KEY_TEST = stringPreferencesKey("PREFERENCES_KEY_TEST")

        /**
        Object name is test class name, which is autogenerated.
        Ending in mock, expected, msg and e.t.c. names is test method name.
         */
        object CreateDataStore_androidKtTest {
            const val mock_editDataStoreData = "hello"
            const val expect_editDataStoreData = "hello"
            const val msg_editDataStoreData: String = "value is not equals"
        }
    }

    object HomeScreen {
        const val flexibleTopAppBar = "flexibleTopAppBar"
        const val contentScroll = "contentScroll"
    }
}
